select description from crime_scene_reports where day = "28" and month = "7" and year = "2020" and street = "Chamberlin Street";
select transcript from interviews where day = "28" and month = "7" and year = "2020" and transcript like "%courthouse%";
select name from people join courthouse_security_logs on people.license_plate = courthouse_security_logs.license_plate where day = "28" and month = "7" and year = "2020" and hour = "10" and minute >= "15" and minute < "25" and activity = "exit";
select distinct name from people join bank_accounts on people.id = bank_accounts.person_id join atm_transactions on bank_accounts.account_number = atm_transactions.account_number where day = "28" and month = "7" and year = "2020" and transaction_type = "withdraw" and atm_location = "Fifer Street";
select name from people join passengers on people.passport_number = passengers.passport_number where flight_id = (select id from flights where day = "29" and month = "7" and year = "2020" order by hour, minute limit 1);
select name from people join phone_calls on people.phone_number = phone_calls.caller where day = "28"  month = "7" and year = "2020" and duration < "60";
select name from people JOIN passengers ON people.passport_number = passengers.passport_number WHERE flight_id = (SELECT id FROM flights WHERE day = "29" AND month = "7" AND year = "2020" ORDER By hour, minute LIMIT 1) INTERSECT SELECT DISTINCT name FROM people JOIN bank_accounts ON people.id = bank_accounts.person_id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE day = "28" AND month = "7" AND year = "2020" AND transaction_type = "withdraw" AND atm_location = "Fifer Street" INTERSECT SELECT name FROM people JOIN phone_calls ON people.phone_number = phone_calls.caller WHERE day = "28" AND month = "7" AND year = "2020" AND duration < "60" INTERSECT SELECT name FROM people JOIN courthouse_security_logs ON people.license_plate = courthouse_security_logs.license_plate WHERE day = "28" AND month = "7" AND year = "2020" AND hour = "10" AND minute >= "15" AND minute < "25" AND activity = "exit";
SELECT city FROM airports WHERE id = (SELECT destination_airport_id FROM flights WHERE day = "29" AND month = "7" AND year = "2020" ORDER BY hour,minute LIMIT 1);
SELECT name FROM people JOIN phone_calls ON people.phone_number = phone_calls.receiver WHERE day = "28" AND month = "7" AND year = "2020" AND duration < "60" AND caller = (SELECT phone_number FROM people WHERE name = "Ernest");
